### ISSUE TITLE
aarch64 build?

### ISSUE THREAD

**Issue by poetaster** [walokra/falldown#1]
I can help get it into chum on the sailfish build server to make this automagical for you...

**Comment by poetaster** [comment]
Building tests at: https://build.sailfishos.org/package/show/home:poetaster:falldown/falldown

Meta repository stanza:
```
  </repository>
  <repository name="sailfish_4.1.0.24_aarch64">
    <path project="sailfishos:4.1.0.24" repository="latest_aarch64"/>
    <arch>aarch64</arch>
  </repository>
```

**Comment by walokra** [comment]
Thanks for the iniative. 

Falldown is already on OBS (https://build.sailfishos.org/package/show/home:walokra:sailfishos/falldown) but as noted it lacks the aarch64 build. I will check how I get the architechture to build and promote it.
